import { withTV } from 'tailwind-variants/transformer';

const config = withTV({
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic': 'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
      },
      // closest color names generated by https://www.color-name.com
      colors: {
        'blue-violet': '#762bff',
        'bright-gray': '#ededed',
        'bright-gray-2': '#e9ebf4',
        'chinese-black': '#141414',
        'light-gray': '#d3d3d3',
      },
      height: {
        108: '27rem',
        150: '37.5rem',
      },
    },
  },
  plugins: [],
});

export default config;
